# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: men-demo

# 定义命名空间
namespace: serverless-test

# tags
env: dev
createMethod: knative

imageName: outer-image # 默认先使用deploy中定义的imageName, 如果deploy中未定义, 使用本行定义的imageName
imageTag: latest
pullPolicy: IfNotPresent
register: bu6.io

# 终止日志
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File

kservices:
  - kserviceName: test-dp1 # 需要唯一
    enabled: false
    imageName: test-image1
    command : ["command"]
    args: ['--arg3', 'value3', '--arg2', 'value2']
    ports:
      - name: http   # 给端口命名
        containerPort: 8080
    # 资源控制
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

sealedSecret:
  enabled: false

configMap:
  enabled: true
  name: config
  spec:
    env: dev
