# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: men-demo

# 定义命名空间
namespace: prod-cs-front

# tags
env: prod
tier: backend # or frontend, cache, db....
customerFacing: "true" # or false
createMethod: ci

imageName: outer-image  # 默认先使用deploy中定义的imageName, 如果deploy中未定义, 使用本行定义的imageName
imageTag: latest
pullPolicy: IfNotPresent
register: bu6.io

# 终止日志
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File

deployments:
  - deploymentName: men-demo # 需要唯一
    enabled: true
    replicaCount: 2
    fluentdTag: cs-front.men-demo.prod
    # command : ["command"]
    # args: ['--arg3', 'value3', '--arg2', 'value2']
    ports:
      - name: http   # 给端口命名
        containerPort: 8080
    # 资源控制
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    # 存活探针
    # 就绪探针
    nodeSelector: {}
    tolerations: []
    affinity: true
    service:
    - name: men-demo   # 需要唯一
      annotations:
        prometheus.io/scrape: 'true'
      type: ClusterIP
      ports:
      - name: http
        port: 80
        targetPort: http # 和下面定义的ports[int].name一致

sealedSecret:
  enabled: false
  path: sealedsecrets/prod/sealsecret.yaml

configMap:
  enabled: true
  name: config
  spec:
    env: prod
