HW.lang = {
    getCurrentLang:function(){
        /*
        * @return {string} "zh" or "en"
        * @algorithm:
        *   直接取当前的语言类型
        * */
        return HW.GlobalState.appConifg.currentLang || 'zh';
    },
    setCurrentLang:function(lang){
        /*
         * @return {Undefined}
         * @param  {string} lang   "zh" or "en"
         * */
        HW.GlobalState.appConifg.currentLang = lang;
    },
    getLocalString: function(key){
        var lang  = HW.lang.getCurrentLang(), data,value;
        data  = HW.lang[lang];
        if(!data || !key) return;
        return data[key] || " ";
    },
    replaceLocalString:function(selector,context,map){
        /*
        * @param {string|dom} selector
        * @param {dom|string} context
        * @algorithm:
        *   如果查找的元素有localString属性，则进行key/value替换操作
        * */
            selector = selector || '[localString]';
            if(context && arguments.length===2 && typeof context == 'function'){
                map = context;
                context = document;
            }
            context  = context  || document;
            $(selector,context).each(function(){
                        var lang  = HW.lang.getCurrentLang(), data,value,
                            tagName = this.tagName, placeholder,
                            key   = this.getAttribute('localString');
                        data  = HW.lang[lang];
                        if(!data) return false; //没有对应的语言映射直接退出
                        value = data[key];
                        if(!key || !value) return true;   //没有映射关键字，不处理;要替换的文本不存，不处理
                        if(map && typeof map == 'function') value = map(value);

                        switch(tagName){
                            case 'INPUT':
                                placeholder = this.getAttribute('placeholder');
                                if(placeholder){
                                    this.setAttribute('placeholder',value);
                                }
                                else{
                                    this.setAttribute('value',value);
                                }
                            case 'TEXTAREA':
                                placeholder = this.getAttribute('placeholder');
                                if(placeholder){
                                    this.setAttribute('placeholder',value);
                                }
                                break;
                            default :
                                $(this).html(value);

                        }

            });
    },
    //key命名pagename_key
    'zh':{
        //公共
       'common_home':'返回',
       'common_homeH':'首页',
       'common_back':'返回',
       'common_more':'查看更多',
       'common_more_only':'更多',
       'common_filter':'筛选',
       'common_confirm':'确认',
       'common_clear':'清除条件',
       'common_cancel':'取消',
       'commnon_clear_search':'清除查询历史',
       'common_no_records':'没有相关内容',
       'common_confirm_delete':'确定清除吗?',
       
       //首页
       'index_login':'登录',
       'index_file':'产品文档',
       'index_cases':'案例',
       'index_news':'公告',
       'index_follow':'我的关注',
       'index_tools':'工具',
       'index_video':'视频',
       'index_command':'命令查询',
       'index_alarm':'告警查询',
       'index_data':'期刊',
       'index_download':'我的下载',
       'index_favorites':'我的收藏',
       'index_favorites_product':'产品',
       'index_favorites_doc':'文档',
       'index_favorites_feedback':'意见',
       'index_favorites_no_product':'暂无产品收藏，快去添加收藏吧',
       'index_favorites_no_doc':'暂无文档收藏，快去添加收藏吧',
       'index_no_login_begin':'您尚未登录，请先',
       'index_no_login_middle':'登录',
       'index_no_login_end':'。',
       'index_no_login':'您尚未登录，请先登录。',
       'index_history':'历史浏览',
       'index_search':'请输入关键字',
       'index_contact':'联系我们',
       'config_header_asendEmail':'应用反馈',
       'index_setting':'设置',
       'index_left_interests':'我的关注',
       'index_favs':'收藏',
       //全局搜索
       'index_left_search':'搜索',
       'index_left_Clear':'取消',
       'search_history':'搜索历史',
       'search_type':'类型',
       'search_language':'语言',
       'search_format':'文件格式',
       'search_product':'产品',
       'search_release_date':'发布时间',
       'search_start_date':'开始时间:',
       'search_end_date':'结束时间:',
       'search_date_placeholder':'日/月/年',
       'search_key_one':'您输入的字符过短，为了提升您的搜索准确度请输入两个以上字符，谢谢！',
        'gs_all_time':'全部时间',
        'gs_Last_week':'最近一周',
        'gs_Last_month':'最近一月',
        'gs_Last_six_months':'最近半年',
        'gs_Last_year':'最近一年',
        'gs_Set_search_time':'自定义时间范围',
        'gs_Set_search_tips0':'登录',
        'gs_Set_search_tips1':'后可找到更多结果',



       //我的收藏
       'favorites_clear_all':'全部删除',
       'favorites_clear':'删除',
       'favorites_back':'取消',
       
       //产品文档
       'pro_category':'产品大全',
       'pro_history':'最近浏览',
       'pro__history':'已关注产品',
       'pro_search':'请输入产品名称',
        'pro_attention_suc':'关注成功',
        'pro_attention_fail':'关注失败',
        'pro_attention_suc_cancel':'取消成功',
        'pro_attention_fail_cancel':'取消失败',
        'pro_attention_suc_set':'保存成功',
        'pro_attention_fail_set':'保存失败',
        //  案例库
       'case_library':'案例',
       'case_file':'文档',
       'case_fault_type':'类型',
       'case_total':'共',
       'case_tips':'条结果',
        'case_reative':'相关案例',
       'case_fault_content':'故障详情',
        // 意见反馈
       'case_feedback':'反馈',
       'feedback':'意见反馈',
       'feedback_tip0':'请您为该文章评分',
       'feedback_tip1':'该文章是否解决了您的问题',
       'feedback_tip2':'最大可输入',
       'feedback_tip3':'个字符',
       'feedback_bad':'很差',
       'feedback_good':'非常好',
       'feedback_yes':'是',
       'feedback_no':'否',
       'feedback_submit':'提交',
       'feedback_textarea':'请输入您的意见',
       'feedback_textareaBad':'差',
       'feedback_textareaGood':'好',
       'feedback_ThankYous':'意见已提交，感谢您的反馈',
       'feedback_failedLater':'网络异常，意见提交失败，请稍后再试',
        //产品目录
       'doc_version':'版本号',
       'doc_type':'文档类型',
       'dir_download':'下载',
       'dir_directory':'目录',
       'doc_content_manual':'详情',
       'doc_fav_tip':'长按产品，可将其添加到我的收藏',
       //文档列表页
       'doc_list_file':'产品文档',
       'doc_list_cases':'案例',
       'doc_list_no_doc':'暂无记录',
       
       
       
        //下载
       'download_manager':'下载管理',
       'download_delAll':'清空',
       'download_edit':'编辑',
       'download_path':'文档路径',
       'download_finish':'已完成',
       'download_loading':'正在下载',
       'download_search':'请输入文档名称',
       'download_search_msg':'请输入搜索关键字',
        // 公告
       'bulletin_file':'公告',
       'bulletin_search':'搜索',
       'bulletin_new':'公告',
       'bulletin_menubar':'menuBar',
       'bulletin_site':'新闻',
       'bulletin_eox':'EOX公告',
       'bulletin_alarm':'预警整改',
       'bulletin_PCN':'PCN',
        //公告搜索
       'bulletin_search_title':'公告搜索页',
       'bulletin_search_tip':'在当前栏目中搜索',
       'bulletin_search_header':'公告搜索',
       'bulletin_search_search':'请输入关键字',
       'bulletin_tips':'提示: 登录后可能找到更多结果',
       'bulletin_detail_title':'公告详细内容显示',
       'bulletin_detail_header':'公告详情',
       //注册
        'signIn_title':'登录',
        'signIn_sign':'注册',
        'signIn_header':'登录',
        'signIn_uid':'Support网站账号',
        'signIn_password':'密码',
        'signIn_savepwd':'记住密码',
        'signIn_auto':'自动登录',
        'signIn_submit':'登录',
        'signIn_tip':'友情提醒：若未勾选自动登录，30分钟后将自动退出',
        'signIn_forget_password':'忘记密码？',
       //siteSearchList
        'siteSearchList_title':'搜索结果',
        'siteSearchList_cancel':'取消',
        'siteSearchList_search':'请输入关键字',
        'siteSearchList_type':'文档',
        'siteSearchList_knowledge':'案例',
        'siteSearchList_other':'公告与其它',
        'siteSearchList_zh':'中文',
        'siteSearchList_en':'英文',
        'siteSearchList_history':'查询历史',
        'siteSearchList_tips0':'没有找到相关结果',
        'siteSearchList_tips1':'网络连接失败，请稍后再试',
        'gs_keywords_invalid':'关键字不合法!',
        //我的空间
        'myZone_title':'我的空间',
        'myZone_logout':'注销',
        'myZone_header':'我的空间',
        'myZone_name':'姓名',
        'myZone_company':'公司',
        'myZone_gender':'性别',
        'myZone_tel':'联系电话',
        'myZone_Email':'Email',
        'myZone_attention':'关注更新',
        'myZone_feedback':'反馈信息',
        'myZone_apply':'我的申请',
        'myZone_agent':'我的待办',
        'myZone_privilege':'权限提升',
        //联系华为
        'contactHW_title':'联系我们',
        'contactHW_header':'联系我们',
        'contactHW_country':'国家',
        'contactHW_TACName':'TAC名称',
        'contactHW_TACHot':'TAC热线',
        'contactHW_email':'服务邮箱',
        'contactHW_send':'发送',
        //我的收藏
        'myFavorites_title':'我的收藏',
        'myFavorites_manage':'管理',
        'myFavorites_tips':'确定删除选择项？',
        'myFavorites_cancel':'取消',
        'myFavorites_delete':'删除',
        'myFavorites_no_product':'请选择一个产品',
        'myFavorites_no_doc':'请选择一个文档',

        //发送邮件
        'sendEmail_title':'发送邮件',
        'sendEmail_content':'请输入您的信息',
        'sendEmail_submit':'提交',
        //js中的
        //产品文档
         'doc_detail_last_dir':'上一章节',

         'doc_detail_next_dir':'下一章节',

        'doc_added_to_favorites':'收藏成功',
        'doc_added_to_favorites_fail':'收藏失败',
        'pro_history_no_data':'没找到最近浏览相关数据',
        'abnormal_network':'网络异常，请稍后再试',
        'abnormal_network_timeout':'网络连接超时，请稍后再试',
        'abnormal_network_try':'系统忙，请稍后再试',
        'pro_product_no_data':'您还没有浏览的产品记录',
        'product_relative_no_data':'没有找到相关产品',
        'product_attention_no_data':'您还没有添加关注产品',
        'entire':'全部',
		'lastr_update':'最近更新',
        'document_relative_no_data':'找不到相关文档',
        'records_relative_no_data':'找不到相关记录',
        'set':'设置',
        'cancel':'取消',
        'download_no_format':'没有选择下载格式',
        'download_no_fail':'无相关文档下载',
        'ask_download':'确定要下载吗？',
        'format':'格式',
        'size':'大小',
        'attachment':'附件',
        'feed_back_tips':'感谢您对我们知识库文章提供的宝贵意见',
        'bulletin_no_news':'暂无新公告',
        'bulletin_search_js_tips':'请输入搜索关键字',
        'bulletin_search_no_relevant':'没有搜索到相关公告',
        'bulletin_search_name_error':'请检查输入的产品名称有无错误',
        'bulletin_search_other_word_try':'请尝试其他查询词',
        'bulletin_search_common_word':'请改用较常见的字词',
        'contactHW_call_tel':'拨打',
        'download_manager_more':'查看更多',
        'download_manager_empty_records':'记录为空',
        'favorite_empty_records':'暂无收藏',
        'download_manager_finished':'完成',
        'download_manager_loading':'下载中',
        'download_manager_wait':'等待',
        'download_manager_stop':'暂停',
        'download_manager_failed':'失败',
        'download_manager_del_data':'确定删除所有数据?',
        'download_manager_doc_path':'文档路径 ',
        'download_manager_ask_del_opt':'确定删除选择项？',
        'download_manager_ask_clear_opt':'确定清空全部？',
        'download_manager_del_local_file':'删除本地文件',
        'download_manager_load_failed':'加载列表失败',
        'myAttention_load_failed':'获取关注更新失败',
        'myZone_js_logout':'您确定要注销吗?',
        'myZone_js_login':'登录',
        'sendEmail_js_failed':'邮件发送失败，请稍后重试',
        'sendEmail_js_success':'您的信息已被接收，我们将尽快进行处理',
        'sendEmail_js_empty_context':'内容不能为空',
        /*dong*/
        /*setuplanguage.js*/
        'textVisible_lev':'语言切换中...',
        /*signIn.js*/
        'nameSingd':'请输入帐号',
        'accountDfill':'账号的长度不能大于50个字符，请重新填写。',
        'passwordDenter':'请输入密码',
        'passwordDfill':'密码的长度不能大于50个字符，请重新填写。',
        'verDcode':'请填写验证码',
        'verDfour':'验证码为4个字符',
        'registerDres':'您将转入注册页进行注册，注册完成需要重启应用。',
        'registerDmanually':'您将转入注册页进行注册，注册完成需要手动返回。',
        /*siteSearchList.js*/
        'nhistoryDs':'暂无搜索记录',
        'foundDs':'找到',
        'articleDs':'条结果',
        'tipDs':'提示: 登录后可能找到更多结果',
        'load_more':'加载更多',
        'gs_load_more':'向上拉加载更多...',
        'gs_loading_more':'加载中...',
        'gs_Release_refresh':'释放刷新...',
        //core
        'core_nativePages_contactHW':'联系华为',
        'core_nativePages_downloadManager':'下载管理',
        'core_nativePages_myFavorites':'我的收藏',
        'core_nativePages_about':'关于',
        'core_nativePages_help':'帮助',
        'core_nativePages_userHelp':'使用帮助',
        'core_login_failed':'登录失败：用户名或密码错误',
        'core_auto_login_failed':'自动登录失败',
        'core_login_out_failed':'注销失败',
        'core_alert_tips':'提示信息',
        'core_alert_confirm':'确认',
        'core_alert_cancel':'取消',
        'index_alert_no_open':'功能暂未开放，敬请期待',


        /*mwx121*/
        //设置config.html
        'config_header_left_btn':'返回',
        'config_header_h1':'设置',
        'config_header_lang':'语言',
        'config_header_lang_zh':'简体中文',
        'config_header_lang_en':'English',
        'config_header_log':'发送异常日志',
        'config_header_wifi':'仅wifi模式下载',
        'config_header_jumpPage_index':'返回',
        'config_header_jumpPage_attention':'我的关注',
        'config_header_update':'检测更新',
        'config_header_clear_cache':'清除缓存',
        'config_header_about':'关于',
        'config_header_help':'帮助',

        //setuplanguage.html
        'setuplanguage_header_left_btn':'返回',
        'setuplanguage_header_right_btn':'完成',
        'setuplanguage_header_h1':'语言',
        'setuplanguage_lang_zh':'简体中文',
        'setuplanguage_lang_en':'English',

        //setupPage.html
        'setupPage_header_left_btn':'返回',
        'setupPage_header_right_btn':'完成',
        'setupPage_header_h1':'登录后跳转页面设置',
        'setupPage_index':'返回',
        'setupPage_attention':'我的关注',

        //asendEmail.html
        'asendEmail_header_left_btn':'返回',
        'asendEmail_header_right_btn':'发表',
        'asendEmail_header_h1':'发送邮件',
        'asendEmail_textarea':'请输入内容',
        'asendEmail_uName':'姓名',
        'asendEmail_uPhone':'电话',
        'asendEmail_uMail':'您的邮箱：',
        //asendEmail.js
        'asendEmail_form_check':'内容不能为空',
        'asendEmail_sendInfo':'发送中...',
        'asendEmail_send_fail':'发送失败，点击重新发送。',
        'asendEmail_send_ok':'邮件发送成功，感谢您提供的宝贵意见',

        //about.html
        'about_header_left_btn':'返回',
        'about_header_h1':'关于',

        //reg.html
        'reg_header_left_btn':'返回',
        //caseContent.js
        'case_content_phenomenon':'现象描述',
        'case_content_alarm_info':'告警信息',
        'case_content_analysis':'原因分析',
        'case_content_process':'处理过程',
        'case_content_conclusion':'建议与总结',
        
        //orderSearch.js
        'orderSearch':'命令查询',
        'orderSearch_key':'请输入命令',
        'wariningSearch_key':'请输入告警',
        'orderSearch_range':'查询范围',
        'orderSearch_login_tip':'登录后可能搜索到更多结果',
        'orderSearch_detail':'命令详情',
        'orderSearch_func':'命令功能',
        'orderSearch_format':'命令格式',
        'orderSearch_param':'参数说明',
        'orderSearch_model':'模式',
        'orderSearch_dclass':'缺省级别',
        'orderSearch_class':'级别',
        'orderSearch_view':'视图',
        'orderSearch_task':'任务名称和操作类型',
        'orderSearch_manul':'使用指南',
        'orderSearch_int':'使用实例',
        'orderSearch_out':'输出说明',

        //warningSearch.js
        'warningSearch':'告警查询',
        'warningSearch_key':'请输入关键字或ID',
        //editorOrderSearch.js
        'editorOrderSearch_range':'查询范围',
        'editorOrderSearch_set':'完成',
        'editorOrderSearch_all_pro':'全部产品',
        'warningSearch_des':'告警解释',
        'warningSearch_attr':'告警属性',
        'warningSearch_affect':'对系统的影响',
        'warningSearch_cause':'可能原因',
        'alarmrelatedinformation':'告警参数',
        'warningSearch_method':'处理步骤',
        'warningSearch_clear':'告警清除',
        'orderSearch_js_pro_all':'所有产品',
        'orderSearch_js_focus':'我的关注',
        'orderSearch_js_total':'共',
        'orderSearch_js_totala':'共',
        'orderSearch_js_record':'条记录',
        'orderSearch_js_null':'无',
        'orderSearch_js_focus_pro':' 我收藏的产品',
        'orderSearch_js_login_focus':'登录后可选择“我关注的产品”',
        'helpsupport':'华为技术支持',
        'helpFullneeds':'功能全面 满足业务需求',
        'setAllsearch':'搜索',
        'Recently':'最近反馈',
        'setadmin':'管理',
        'pro_categorying':'已关注产品',
        /*myApplyFor.html*/
        'SoftwareRequests':'软件申请',
        'AssociationRequests':'关联渠道',
        'ContributedArticles':'投稿申请',
        'ProductRegistration':'产品注册',
        'applyforall':'全部',
        'searchScope':'选择查询范围',
        'myToDo':'我的待办',
        'youLogdo':'您还没有登录，现在登录吗？',
        'Loginattentionyou':'登录后才可看相关关注，现在登录吗？',
        'Loginattentionyou_reload':'登录超时，确定要重新登录吗？',
        'relatedConcerns':'您未设置任何关注的产品，请先设置',
        'PleaseProduct':'请选择产品',

        'NameNotempty':'姓名不能空',
        'PhoneNotempty':'电话不能为空',
        'PleaseValidnumber':'请输入正确的手机号码',
        'PleaseEmailaddress':'请输入正确的邮箱地址',
        'ManageBtnadd':'您还没有关注产品，请点击  管理按钮  进行添加',
        'Meetrequirements':'没有找到符合要求内容',
        'FailedOKresend':'发送失败，点击确定重新发送',
        'ReplyNotempty':'回复内容不能空',
        'ReplyTosuccess':'回复成功',
        'PleaseRateArticle':'请为文章评分',
        'OpinionNoempty':'意见内容不能为空',
        'SubmitSuccess':'提交成功',
        'NoRespite':'暂无内容',
        'WillUseRegistration':'将使用浏览器跳转到注册页面注册，确定吗？',
        'WillUseForget':'将使用浏览器跳转到忘记密码页面，确定吗？',
        'browserumpyou':'将使用浏览器跳转到权限提升页，确定吗？',
        'browserPage':"将使用浏览器打开页面，确定吗？",

        'Applicant':'申请人',
        'ApplicationNumber':'申请号',
        'Pleaseenterapplicant':'请输入申请人',
        'Pleaseenternumber':'请输入申请号',
        'Softwareapplications':'软件申请',
        'Appversionnumber':'申请版本号',
        'AddMyFavorites':'添加到我的收藏',
        'NoName':'无名称',
        'Audit':'审核中',
        'Pass':'通过',
        'Refuse':'拒绝',
        'Handler':'处理人',
        'adminAccount':'渠道公司管理员账号',
        'CompaniesApply':'关联渠道公司申请',
        'Title':'标题',
        'ProductRegistration':'产品注册',
        'ProductName':'产品名称',
        'Requisitionempty':'申请单号不能为空',
        'Doesapply':'没有申请',
        'ApplicationInstructions':'申请说明',
        'Manuscripttitle':'稿件标题',
        'SearchNotempty':'搜索框不能为空',
        'FollowingProduct':'已关注的产品',
        'EntireEntire':'全部 \\ 全部',
        'Reply':'回复',
        'Pleasereply':'请输入您的回复',
        'Pleaserequisitionno':'请输入申请单号',

        //add by mwx121
        'backfeedProductFail':"提交失败，文档目录不存在。" ,
        'ask_download_wifi':"请您切换到WIFI网络模式下进行下载。" ,
        'attention2LoginInfo':"您还未登录，请先登录？",
        'bookmarkPage':"收藏本页后，请到我的收藏中查看收藏结果",
        'bookmarkEnterPageName':"请输入页面名称",
        'unableCheck':'无法连接网络，请检查',
        'config_header_jumpPagea':'登录首页',
        'saveE':'保存',
        'sureR':'确定',
        'signInTimeOut':"登录超时，请重新登录。",
        'index_newsD':'应用下载',
        'ios_newsD':'苹果版下载',
        'android_newsD':'安卓版下载',
        'newPubTime':"发布时间: ",
        'appDown_Ios_tip':'您的手机是Android系统，确定要下载IOS安装包吗？',
        'appDown_android_tip':'您的手机是IOS系统，确定要下载Android安装包吗？',
        'attention_add_product':'添加产品',
        'attention_add_now':'添加关注产品',
        'relatedConcernsUpdate0':'您关注的产品，暂无产品文档更新',
        'relatedConcernsUpdate1':'您关注的产品，暂无知识库更新',
        'relatedConcernsUpdate2':'您关注的产品，暂无公告更新',
        'update':'更新',
        'last_search_oa':'查询历史',
        'no_download_doc_at':'没有可供下载的文档或者附件' ,
        'warningSearch_des_v8':  'Trap Buffer信息解释',
        'warningSearch_attr_v8':'Trap属性',
        'alarmrelatedinformation_v8':'Trap Buffer信息参数',
        'order_warning_pession':'很抱歉，您当前账号无权进行此操作',
        'about_info':'更多信息请访问',

         //his.html
        'history_clear_all':'全部删除',
        'history_doc_list_file': '产品文档',
        'history_doc_list_cases':"案例",
        'history_list_no_doc':'没有“历史浏览”相关内容',
        'history_del_record':'是否删除所有的历史记录?'
    },
    'en':{
        'common_home':'Back',
        'common_homeH':'Home',
        'common_back':'Back',
        'common_more':'View more',
        'common_more_only':'More',
        'common_filter':'Filter',
        'common_confirm':'OK',
        'common_clear':'Clear Criteria',
        'common_cancel':'Cancel',
        'commnon_clear_search':'Clear history',
        'common_no_records':'No queried records exist.',
        'common_confirm_delete':'Are you sure you want to clear the history?',
        'gs_keywords_invalid':'Invalid keywords!',
        'index_login':'Log in',
        'index_file':'Documents',
        'index_cases':'Cases',
        'index_news':'News',
        'index_follow':'Interested',
        'index_tools':'Query',
        'index_video':'Videos',
        'index_command':'Command',
        'index_alarm':'Alarm',
        'index_data':'Newsletter',
        'index_download':'Downloads',
        'index_favorites':'Favorites',
        'index_favorites_product':'Products',
        'index_favorites_doc':'Documents',
        'index_favorites_feedback':'Comments',
        'index_favorites_no_product':'No favorites exist. Please add a favorite.',
        'index_favorites_no_doc':'No favorites exist. Please add a favorite.',
        'index_no_login_begin':'Please ',
        'index_no_login_middle':'log in',
        'index_no_login_end':' to view',
        'index_no_login':'Please log in to view.',
        'index_history':'Browse History',
        'index_search':'Enter keywords',
        'index_contact':'Contact Us',
        'config_header_asendEmail':'Feedback',
        'index_setting':'Settings',
        'index_left_interests':'Interested',
        'index_favs':'Add to Favorites.',
        'index_left_search':'Search',
        'index_left_Clear':'Clear',
        'doc_detail_last_dir':'Previous Chapter',
        'doc_detail_next_dir':'Next Chapter',
        'search_history':'Queried Records',
        'search_type':'Type',
        'search_language':'Language',
        'search_format':'Format',
        'search_product':'Product',
        'search_release_date':'Release Date',
        'search_start_date':'From:',
        'search_end_date':'To:',
        'gs_all_time':'All',
        'gs_Last_week':'Last week',
        'gs_Last_month':'Last month',
        'gs_Last_six_months':'Last six months',
        'gs_Last_year':'Last year',
        'gs_Set_search_time':'Set search time',
        'gs_Set_search_tips0':'log in',
        'gs_Set_search_tips1':'for more search results',
        'search_date_placeholder':'DD/MM/YYYY',
        'gs_load_more':'Pull up to load more...',
        'gs_loading_more':'Loading...',
        'gs_Release_refresh':'Release to refresh...',
        //我的收藏
        'favorites_clear_all':'Clear All',
        'favorites_clear':'Clear',
        'favorites_back':'Back',
        
        'pro_category':'Product Category',
        'pro_history':'History',
        'pro__history':'Interested products',
        'pro_search':'Please enter a keyword',
        'case_library':'Cases',
        'case_file':'Documents',
        'case_fault_type':'Type',
        'case_reative':'Related cases',
        'case_total':' ',
        'case_tips':'records found',
        'case_fault_content':'Error',
        'case_feedback':'FeedBack',
        'feedback':'FeedBack',
        'feedback_tip0':'Please rate this Knowledgebase Articles',
        'feedback_tip1':'Does this Knowledgebase Articles help you to solve your problem?',
        'feedback_tip2':'Maximum input',
        'feedback_tip3':'characters',
        'feedback_bad':'Bad',
        'feedback_good':'Good',
        'feedback_yes':'Yes',
        'feedback_no':'No',
        'feedback_submit':'Submit',
        'feedback_textarea':'Please input your feedback',
        'doc_version':'Version',
        'doc_type':'Document Type',
        'dir_download':'Download',
        'dir_directory':'Contents',
        'doc_content_manual':'Details',
        'doc_fav_tip':'Touch and hold to add to Favorites',
        'feedback_textareaBad':'Poor',
        'feedback_textareaGood':'Excellent',
        'feedback_ThankYous':'Thank you for your feedback.',
        'feedback_failedLater':'Failed to submit feedback due to a network error. Please try later.',
        //文档列表页
        'doc_list_file':'Product Info',
        'doc_list_cases':'Cases',
        'doc_list_no_doc':'No record exist',
        
        'bulletin_file':'News',
        'bulletin_search':'Search',
        'bulletin_new':'Bulletins',
        'bulletin_menubar':'menuBar',
        'bulletin_site':'News',
        'bulletin_eox':'EOX',
        'bulletin_alarm':'Precaution Notice',
        'bulletin_PCN':'PCN',
        'pro_attention_suc':'Product added',
        'pro_attention_fail':'Failed to add the product',
        'pro_attention_suc_cancel':'Product removed',
        'pro_attention_fail_cancel':'Failed to remove the product',
        'pro_attention_suc_set':'Product saved',
        'pro_attention_fail_set':'Failed to save the product',
        //公告搜索
        'bulletin_search_title':'Search',
        'bulletin_search_tip':'Search current tab',
        'bulletin_search_header':'News Search',
        'bulletin_search_search':'Please enter a keyword',
        'bulletin_tips':'Tip: Login may find more results',
        'bulletin_detail_title':'News',
        'bulletin_detail_header':'News',
        //注册
        'signIn_title':'Log in',
        'signIn_sign':'Register',
        'signIn_header':'Log in',
        'signIn_uid':'Support website account',
        'signIn_password':'Password',
        'signIn_savepwd':'Remember Password',
        'signIn_auto':'Auto Login',
        'signIn_submit':'Log In',
        'signIn_tip':'Note: If Auto Login is not selected, you will be automatically logged out after 30 minutes',
        'signIn_forget_password':'Forgot password?',
        
        //siteSearchList
        'siteSearchList_title':'Search results',
        'siteSearchList_cancel':'Cancel',
        'siteSearchList_search':'Please enter a keyword',
        'siteSearchList_type':'Documents',
        'siteSearchList_knowledge':'Knowledge',
        'siteSearchList_other':'Notices and others',
        'siteSearchList_zh':'Chinese',
        'siteSearchList_en':'English',
        'siteSearchList_history':'Recent searches',
        'siteSearchList_tips0':'No result found',
        'siteSearchList_tips1':'Network connection fails,  please try again later',
        //我的空间
        'myZone_title':'My space',
        'myZone_logout':'Log out',
        'myZone_header':'My space',
        'myZone_name':'Name',
        'myZone_company':'Company',
        'myZone_gender':'Gender',
        'myZone_tel':'Phone',
        'myZone_Email':'Email',
        'myZone_attention':'Attention',
        'myZone_feedback':'FeedBack',
        'myZone_apply':'My Application',
        'myZone_agent':'To-dos',
        'myZone_privilege':'Get access privileges',
        //联系华为
        'contactHW_title':'Contact us',
        'contactHW_header':'Contact us',
        'contactHW_country':'Country',
        'contactHW_TACName':'TAC Name',
        'contactHW_TACHot':'TAC Hotlines',
        'contactHW_email':'Email',
        'contactHW_send':'Send',
        //下载
        'download_no_format':'Select the format of the document you want to download.',
        'download_manager':'DownLoad',
        'download_delAll':'Clear',
        'download_edit':'Edit',
        'download_path':'Document path',
        'download_finish':'Downloaded',
        'download_loading':'Downloading',
        'download_no_fail':'No documents available for downloads.',
        'download_search':'Enter document name',
        'download_search_msg':'Enter search keywords.',
        'Loginattentionyou_reload':'Login timeout, you sure you want to log in again？',
        //我的收藏
        'myFavorites_title':'My Favorites',
        'myFavorites_manage':'Manage',
        'myFavorites_tips':'Delete selected items? ',
        'myFavorites_cancel':'Cancel ',
        'myFavorites_delete':'Delete',
        'myFavorites_no_product':'Please select a product',
        'myFavorites_no_doc':'Please select a document',
        //发送邮件
        'sendEmail_title':'Send email',
        'sendEmail_content':'Enter your information',
        'sendEmail_submit':'Submit',
        //产品文档
        'doc_added_to_favorites':'Added to Favorites.',
        'doc_added_to_favorites_fail':'Added to Favorites Fail.',
        'pro_history_no_data':'No recent browsing data',
        'pro_abnormal_network':'Abnormal network,  Please try again later',
        'abnormal_network':'Connection timed out. Please try again later',
        'pro_product_no_data':'No product browsing history.',
        'pro_abnormal_network_timeout':'Connection timed out. Please try again later.',
        'abnormal_network_timeout':'Network connection timeout,  Please try again later',
        'pro_abnormal_network_try':'Network anomalies, please try again',
        'abnormal_network_try':'System busy, please try again later',
        'product_relative_no_data':'No products found.',
        'pro_product_relative_no_data':'No related products',
        'product_attention_no_data':'You have not added any interested products yet.',
        'entire':'All',
        'document_relative_no_data':'No documents found.',
        'set':'Settings',
        'cancel':'Cancel',
		'lastr_update':'Recent feedback',
        'records_relative_no_data':'No results found.',
        'ask_download':'Download the document?',
        'format':'Format',
        'size':'Size',
        'attachment':'Attachments',
        'feed_back_tips':'Thanks for your comments on the documents in our knowledge base.',
        'bulletin_no_news':'No new notices.',
        'bulletin_search_js_tips':'Enter keywords before searches.',
        'bulletin_search_no_relevant':'No notices found.',
        'bulletin_search_name_error':'Check that the product name is correct.',
        'bulletin_search_other_word_try':'Try other keywords.',
        'bulletin_search_common_word':'Try some common keywords.',
        'contactHW_call_tel':'Call',
        'download_manager_more':'View more',
        'download_manager_empty_records':'No downloads',
        'favorite_empty_records':'No favorites',
        'download_manager_finished':'Done',
        'download_manager_loading':'Downloading...',
        'download_manager_wait':'Pending...',
        'download_manager_stop':'Paused',
        'download_manager_failed':'Failed',
        'download_manager_doc_path':'Document path',
        'download_manager_del_data':'Delete all data?',
        'download_manager_ask_del_opt':'Delete selected items?',
        'download_manager_ask_clear_opt':'Clear all?',
        'download_manager_del_local_file':'Delete local files?',
        'download_manager_load_failed':'Failed to load the list.',
        'myAttention_load_failed':'Failed to update your interested products.',
        'myZone_js_logout':'Log out of the application?',
        'myZone_js_login':'Log in',
        'sendEmail_js_failed':'Failed to send the email. Please try again later.',
        'sendEmail_js_success':'We have received your message and will handle it as soon as possible.',
        'sendEmail_js_empty_context':'Comments cannot be left empty.' ,
        /*dong*/
        /*setuplanguage.js*/
        'textVisible_lev':'Switching the language...',
        /*signin.js*/
        'nameSingd':'Enter your user name.',
        'accountDfill':'The user name can contain a maximum of 50 characters. Please reenter.',
        'passwordDenter':'Enter your password.',
        'passwordDfill':'The password can contain a maximum of 50 characters. Please reenter.',
        'verDcode':'Enter the verification code.',
        'verDfour':'The verification code contains 4 characters.',
        'registerDres':'You will be redirected to the registration screen. Complete the registration and restart the application.',
        'registerDmanually':'You will be redirected to the registration screen. Complete the registration and return to the login screen.',
        /*siteSearchList.js*/
        'nhistoryDs':'No matching results found.',
        'foundDs':'',
        'articleDs':' records found.',
        'tipDs':'Tip: Login may find more results',
        'load_more':'Load more',
        'search_key_one':'Enter a keyword containing at least tow characters!',
        //core
        'core_nativePages_contactHW':'Contact us',
        'core_nativePages_downloadManager':'Download mgmt',
        'core_nativePages_myFavorites':'Favorites',
        'core_nativePages_about':'About',
        'core_nativePages_help':'Help',
        'core_nativePages_userHelp':'Help',
        'core_login_failed':'Incorrect user name or password. Login failed.',
        'core_auto_login_failed':'Failed to log in automatically.',
        'core_login_out_failed':'Logout failed.',
        'core_alert_tips':'Note',
        'core_alert_confirm':'OK',
        'core_alert_cancel':'Cancel',
        'index_alert_no_open':'This function is not available yet.',

        /*mwx121*/
        //设置config.html
        'config_header_left_btn':'Back',
        'config_header_h1':'Settings',
        'config_header_lang':'Language',
        'config_header_lang_zh':'简体中文',
        'config_header_lang_en':'English',
        'config_header_log':'Send exception logs',
        'config_header_wifi':'Download over Wi-Fi only',
        'config_header_jumpPage_index':'Home page',
        'config_header_jumpPage_attention':'Interested',
        'config_header_update':'Check for updates',
        'config_header_clear_cache':'Clear cache',
        'config_header_asendEmail':'Feedback',
        'config_header_about':'About',
        'config_header_help':'Help',

        //setuplanguage.html
        'setuplanguage_header_left_btn':'Back',
        'setuplanguage_header_right_btn':'Done',
        'setuplanguage_header_h1':'Language',
        'setuplanguage_lang_zh':'简体中文',
        'setuplanguage_lang_en':'English',

        //setupPage.html
        'setupPage_header_left_btn':'Back',
        'setupPage_header_right_btn':'Done',
        'setupPage_header_h1':'Set the page you want to be redirected to after login',
        'setupPage_index':'Home page',
        'setupPage_attention':'Interested products',

        //asendEmail.html
        'asendEmail_header_left_btn':'Back',
        'asendEmail_header_right_btn':'Submit',
        'asendEmail_header_h1':'Send email',
        'asendEmail_textarea':'Provide your feedback.',
        'asendEmail_uName':'Name',
        'asendEmail_uPhone':'Phone',
        'asendEmail_uMail':'Your email:',
        //asendEmail.js
        'asendEmail_form_check':'Comments cannot be left empty.',
        'asendEmail_sendInfo':'Sending...',
        'asendEmail_send_fail':'Failed to send. Touch OK to resend.',
        'asendEmail_send_ok':'Email sent. Thanks for your feedback.',


        //about.html
        'about_header_left_btn':'Back',
        'about_header_h1':'About',

        //reg.html
        'reg_header_left_btn':'Back',
        'reg_reg':'Registration',
        //caseContent.js
        'case_content_phenomenon':'Symptom',
        'case_content_alarm_info':'Alarm',
        'case_content_analysis':'Cause analysis',
        'case_content_process':'Handling process',
        'case_content_conclusion':'Suggestions and summary',
        //orderSearch.js
        'orderSearch':'Commands',
        'orderSearch_key':'Enter command name',
        'wariningSearch_key':' Enter alarm name',
        'orderSearch_range':'Query scope',
        'orderSearch_login_tip':'You may find more results after login.',
        'orderSearch_detail':'Command Info',
        'orderSearch_func':'Function',
        'orderSearch_format':'Format',
        'orderSearch_param':'Parameters',
        'orderSearch_model':'Modes',
        'orderSearch_dclass':'Default Level',
        'orderSearch_class':'Level',
        'orderSearch_view':'Views',
        'orderSearch_task':'Task Name and Operations',
        'orderSearch_manul':'Usage Guidelines',
        'orderSearch_int':'Example',
        'orderSearch_out':'System Response',

        //warningSearch.js
        'warningSearch':'Alarms',
        'warningSearch_key':'Please enter a key or ID',
        'alarmrelatedinformation':'Parameters',
        //editorOrderSearch.js
        'editorOrderSearch_range':'Query scope',
        'editorOrderSearch_set':'Done',
        'editorOrderSearch_all_pro':'All products',
        'warningSearch_des':'Description',
        'warningSearch_attr':'Attribute',
        'warningSearch_affect':'Impact on the System',
        'warningSearch_cause':'Possible Causes',
        'warningSearch_method':'Procedure',
        'warningSearch_clear':'Alarm clearing',
        'orderSearch_js_pro_all':'All products',
        'orderSearch_js_focus':'Interested',
        'orderSearch_js_total':'all',
        'orderSearch_js_totala':'',
        'orderSearch_js_record':'records found',
        'orderSearch_js_null':'No',
        'orderSearch_js_focus_pro':' Interested products',
        'orderSearch_js_login_focus':'After login, you will be able to select Interested products.',
        'helpsupport':'Huawei technical support',
        'helpFullneeds':'Comprehensive functions to fully meet your requirements',
        'setAllsearch':'Search',
        'Recently':'Recently',
        'setadmin':'Manage',
        'pro_categorying':'Interested products',
        /*myApplyFor.html*/
        'SoftwareRequests':'Software application',
        'AssociationRequests':'Associated channels',
        'ContributedArticles':'Document publication',
        'ProductRegistration':'Product registration',
        'applyforall':'All',
        'searchScope':'Select the query scope.',
        'myToDo':'To-dos',
        'youLogdo':'Log in to the application?',
        'Loginattentionyou':'After login, you will be able to view interested products. Log in?',
        'relatedConcerns':'No interested products found. Please add some first.',
        'PleaseProduct':'Select your interested products.',
        'NameNotempty':'The name cannot be left empty.',
        'PhoneNotempty':'The phone cannot be left empty.',
        'PleaseValidnumber':'Enter a valid phone number.',
        'PleaseEmailaddress':'Enter a valid email address.',
        'ManageBtnadd':'No interested products found. Touch Manage to add some.',
        'Meetrequirements':'No matching content found.',
        'FailedOKresend':'Failed to send. Touch OK to resend.',
        'ReplyNotempty':'The reply content cannot be left empty.',
        'ReplyTosuccess':'Message replied.',
        'PleaseRateArticle':'Rate this document',
        'OpinionNoempty':'Please enter the feedback and then touch Submit.',
        'SubmitSuccess':'Feedback submitted.',
        'NoRespite':'No content.',
        'WillUseRegistration':'You will be redirected to the registration page using a browser. Continue?',
        'WillUseForget':'You will be redirected to the password page using a browser. Continue?',
        'browserumpyou':'You will be redirected to the permission update page using a browser. Continue?',
        'browserPage':"A browser will be used to open the page. Continue?",

        'Applicant':'Applicant',
        'ApplicationNumber':'Application No.',
        'Pleaseenterapplicant':'Enter applicant',
        'Pleaseenternumber':'Enter application No.',
        'Softwareapplications':'Software application',
        'Appversionnumber':'Requested version No.',
        'AddMyFavorites':'Add to my favorites',
        'NoName':'No name',
        'Audit':'Reviewing',
        'Pass':'Approved',
        'Refuse':'Rejected',
        'Handler':'Owner',
        'adminAccount':'Channel company\'s administrator account',
        'CompaniesApply':'Associated channel company application',
        'Title':'Title',
        'ProductRegistration':'Product registration',
        'ProductName':'Product Name',
        'Requisitionempty':'The application No. cannot be left empty.',
        'Doesapply':'No applications',
        'ApplicationInstructions':'Application description',
        'Manuscripttitle':'Document title',
        'SearchNotempty':'Enter search keywords.',
        'FollowingProduct':'Interested products',
        'EntireEntire':'All \\ All',
        'Reply':'Reply',
        'Pleasereply':'Enter your reply',
        'Pleaserequisitionno':'Enter application No.' ,

        //add by mwx121
        'backfeedProductFail':"Failed to submit. The document path does not exist.",
        'ask_download_wifi':"Please connect to a Wi-Fi network and download the document." ,
        'attention2LoginInfo':"Log in to the application?",
        'bookmarkPage':"This page will be added to My favorites.",
        'bookmarkEnterPageName':"Enter page name",
        'unableCheck':'No network connections. Check your network settings.',
        'config_header_jumpPagea':'Home',
        'saveE':'Save',
        'sureR':'OK',
        'signInTimeOut':"Login timed out. Please try again.",
        'newPubTime':"Release time:",
        'index_newsD':'Client',
        'ios_newsD':'Ios Download',
        'android_newsD':'Android Download',
        'appDown_Ios_tip':'Your phone is Android system, determine the installation package you want to download IOS?',
        'appDown_android_tip':'Your phone is IOS system to determine the installation package you want to download Android?',
        'attention_add_product':'Add Product',
        'attention_add_now':'Add your interested products',
        'relatedConcernsUpdate0':'No product document updates',
        'relatedConcernsUpdate1':'No case updates',
        'relatedConcernsUpdate2':'No news updates',
        'update':' updates',
        'last_search_oa':'Queried Records',
        'no_download_doc_at':'No documents to download',
        'warningSearch_des_v8':  'Description',
        'warningSearch_attr_v8':'Attribute',
        'alarmrelatedinformation_v8':'Parameters ',
        'order_warning_pession':'Sorry. You do not have the permission to perform this operation',
        'about_info':'For more information, visit',

        //his.html
        'history_clear_all':'Clear All',
        'history_doc_list_file': 'Product Info',
        'history_doc_list_cases':"Cases",
        'history_doc_list_no_doc':'No history record exist',
        'history_del_record':'Delete all history record?'
    }
}